### ISSUE TITLE
var defaults 

### ISSUE THREAD

**Issue by aberel** [makotokw/jquery.ui.potato.menu#4]
var defaults must be INSIDE the function menu() , maybe first of all, because when $extend will affect the global defaults. This occurs when you have more than one menu object in the same page.

So the solution is:
(function($) {
	function menu() {
		var defaults = { [default options here...] };
		var option = (typeof(arguments[0])!='string') ? $.extend(defaults,arguments[0]) : $.extend(defaults,{});
		...

**Comment by makotokw** [comment]
Thanks. I fixed it in v1.2.1.
